import type { NextPage } from 'next'
import Head from 'next/head'
import Keyboard from '../components/keyboard/keyboard'
import WordRow from '../components/wordRow/wordRow'
import styles from '../styles/Home.module.css'
import { BsFillGearFill } from 'react-icons/bs'
import { useState } from 'react'

const Home: NextPage = () => {
  const [answer, setAnswer] = useState("hello".toUpperCase())
  const [error, setError] = useState(false)

  const [hideHint, setHideHint] = useState(true)

  const [currentKey, setCurrentKey] = useState(0)
  const [currentTry, setCurrentTry] = useState(0)

  const [guess1, setGuess1] = useState(Array(answer.length).fill(""))
  const [guess2, setGuess2] = useState(Array(answer.length).fill(""))
  const [guess3, setGuess3] = useState(Array(answer.length).fill(""))
  const [guess4, setGuess4] = useState(Array(answer.length).fill(""))
  const [guess5, setGuess5] = useState(Array(answer.length).fill(""))
  const [guess6, setGuess6] = useState(Array(answer.length).fill(""))

  return (
    <div className={styles.container}>
      <Head>
        <title>Custom Wordle</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <h1>Custom Wordle!</h1>
          <BsFillGearFill size={40} className={styles.settingIcon} />
        </div>
        <button className={styles.myo}>Make your own now!</button>
        <p>Hint: <span className={ hideHint ? styles.hidden : "" }
          onClick={() => setHideHint(false)} >How you greet people</span></p>
        {error ? <p>Word doesn't exist in a dictionary</p> : null}
        <div className={styles.wordContainer}>
          <WordRow answer={answer} guess={guess1} rowNum={0} curTry={currentTry} />
          <WordRow answer={answer} guess={guess2} rowNum={1} curTry={currentTry} />
          <WordRow answer={answer} guess={guess3} rowNum={2} curTry={currentTry} />
          <WordRow answer={answer} guess={guess4} rowNum={3} curTry={currentTry} />
          <WordRow answer={answer} guess={guess5} rowNum={4} curTry={currentTry} />
          <WordRow answer={answer} guess={guess6} rowNum={5} curTry={currentTry} />
        </div>
        <div className={styles.keyboardContainer}>
          <Keyboard wordInd={currentKey} setWordInd={setCurrentKey} 
            curTry={currentTry} setCurTry={setCurrentTry} 
            guesses={[guess1, guess2, guess3, guess4, guess5, guess6]}
            setGuesses={[setGuess1, setGuess2, setGuess3, setGuess4, setGuess5, setGuess6]} />
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with &#128151; from &#127481;&#127469;</p>
      </footer>
    </div>
  )
}

export default Home
